(clear)
(load "main.clp")

(load "env.clp")
(set-break forward-north-bump)
(set-break forward-south-bump)
(set-break forward-east-bump)
(set-break forward-west-bump)
(set-break msg-order-accepted-KO1)
(set-break msg-order-delayed-KO1)
(set-break msg-order-rejected-KO1)
(set-break msg-order-rejected-KO2)
(set-break msg-mng-KO1)
(set-break msg-mng-KO2)
(set-break CheckFinish_useless-1)
(set-break CheckFinish_useless-2)
(set-break CheckFinish_useless-3)
(set-break CheckFinish_useless-4)
(set-break CheckFinish_KO_1)
(set-break CheckFinish_KO_2)
(set-break CleanTable_K0_1)
(set-break CleanTable_K0_2)
(set-break CleanTable_K0_3)
(set-break CleanTable_K0_4)
(set-break CleanTable_K0_5)
(set-break EmptyFood_KO1)
(set-break EmptyFood_KO2)
(set-break EmptyFood_KO3)
(set-break Release_KO1)
(set-break Release_KO2)
(set-break Release_KO3)
(set-break load-food_KO1)
(set-break load-food_KO2)
(set-break load-food_KO3)
(set-break load-food_KO4)
(set-break load-drink_KO1)
(set-break load-drink_KO2)
(set-break load-drink_KO3)
(set-break load-drink_KO4)
(set-break delivery-food_WRONG_2)
(set-break delivery-food_WRONG_3)
(set-break delivery-drink_WRONG_2)
(set-break delivery-drink_WRONG_3)
(set-break delivery_WRONG_4)
(set-break delivery_WRONG_5)

(load "agent.clp")

(load "percept.clp")
(load "strategy1.clp")
;(set-break strategy-search-table-to-serve)
;(set-break strategy-do-CleanTable)
;(set-break strategy-do-EmptyFood)
;(set-break strategy-do-Release)

;(set-break strategy-go-phase1-finish)
;(set-break strategy-return-phase2_finish)
(load "exec-plane.clp")
;(load "manage-order.clp")
(load "a_star.clp")

(reset)
(run 257)
(assert (exec (step 0) (action Forward)))
(assert (debug 2))
(run 3980)
